### ISSUE TITLE
npm start 报错

### ISSUE THREAD

**Issue by taofish** [brickspert/react-family#16]
> react-family@1.0.0 start /Users/wuwentao/Desktop/demo/react-family
> webpack-dev-server --config webpack.dev.config.js --color --progress --hot

 10% building modules 2/2 modules 0 activeevents.js:167                       r       throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8080
    at Server.setupListenHandle [as _listen2] (net.js:1336:14)
    at listenInCluster (net.js:1384:12)
    at doListen (net.js:1510:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1363:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-family@1.0.0 start: `webpack-dev-server --config webpack.dev.config.js --color --progress --hot`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-family@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wuwentao/.npm/_logs/2018-12-24T11_04_33_602Z-debug.log

**Comment by taofish** [comment]
问题已经解决，端口被占用了
